-- Drop database if exists and create new one
DROP DATABASE IF EXISTS hrmsdb;
CREATE DATABASE hrmsdb;
USE hrmsdb;

-- Set character set and collation
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Create Department table
DROP TABLE IF EXISTS `DEPARTMENT`;
CREATE TABLE `DEPARTMENT` (
  `DEPTID` int NOT NULL AUTO_INCREMENT,
  `DEPTNAME` varchar(36) NOT NULL,
  `PARENTID` int DEFAULT NULL,
  PRIMARY KEY (`DEPTID`),
  KEY `PARENTID` (`PARENTID`),
  CONSTRAINT `DEPARTMENT_ibfk_1` FOREIGN KEY (`PARENTID`) REFERENCES `DEPARTMENT` (`DEPTID`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Create UserType table
DROP TABLE IF EXISTS `USERTYPE`;
CREATE TABLE `USERTYPE` (
  `TYPEID` int NOT NULL AUTO_INCREMENT,
  `TYPENAME` varchar(36) NOT NULL,
  PRIMARY KEY (`TYPEID`)
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Create User table
DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `USERID` varchar(50) DEFAULT NULL,
  `FIRSTNAME` varchar(250) NOT NULL,
  `LASTNAME` varchar(250) NOT NULL,
  `STREETADDR` varchar(50) DEFAULT NULL,
  `CITY` varchar(50) DEFAULT NULL,
  `STATE` varchar(2) DEFAULT NULL,
  `ZIPCODE` varchar(50) DEFAULT NULL,
  `TITLE` varchar(50) DEFAULT NULL,
  `MANAGER` varchar(500) DEFAULT NULL,
  `ISMANAGER` char(1) DEFAULT NULL,
  `EDULEVEL` varchar(50) DEFAULT NULL,
  `STATUS` char(1) NOT NULL,
  `DEPTID` int DEFAULT NULL,
  `TYPEID` int DEFAULT NULL,
  `DATE_MODIFIED` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `DEPTID` (`DEPTID`),
  KEY `TYPEID` (`TYPEID`),
  CONSTRAINT `USER_ibfk_1` FOREIGN KEY (`DEPTID`) REFERENCES `DEPARTMENT` (`DEPTID`),
  CONSTRAINT `USER_ibfk_2` FOREIGN KEY (`TYPEID`) REFERENCES `USERTYPE` (`TYPEID`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;




SET FOREIGN_KEY_CHECKS = 1;
